Rscript 00.0_format_sumstats.R GCST000755
Rscript 00.0_format_sumstats.R GCST002216
Rscript 00.0_format_sumstats.R GCST90092808
Rscript 00.0_format_sumstats.R GCST90092809
Rscript 00.0_format_sumstats.R GCST90092826
Rscript 00.0_format_sumstats.R GCST90092875
Rscript 00.0_format_sumstats.R GCST90092928
Rscript 00.0_format_sumstats.R GCST90092975
Rscript 00.0_format_sumstats.R GCST90092980
Rscript 00.0_format_sumstats.R GCST90092981
Rscript 00.0_format_sumstats.R GCST90092985
Rscript 00.0_format_sumstats.R GCST90092987
Rscript 00.0_format_sumstats.R GCST90093002
Rscript 00.0_format_sumstats.R GCST90269502
Rscript 00.0_format_sumstats.R GCST90269582

python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST000755.HDL-cholesterol.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST000755.HDL-cholesterol --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST002216.Triglycerides.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST002216.Triglycerides --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092808.Apolipoprotein-A1-levels.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092808.Apolipoprotein-A1-levels --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092809.Apolipoprotein-B-levels.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092809.Apolipoprotein-B-levels --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092826.Concentration-of-HDL-particles.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092826.Concentration-of-HDL-particles --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092875.Concentration-of-large-VLDL-particles.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092875.Concentration-of-large-VLDL-particles --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092928.Monounsaturated-fatty-acid-levels.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092928.Monounsaturated-fatty-acid-levels --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092975.Concentration-of-small-VLDL-particles.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092975.Concentration-of-small-VLDL-particles --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092980.Saturated-fatty-acid-levels.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092980.Saturated-fatty-acid-levels --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092981.Ratio-of-saturated-fatty-acids-to-total-fatty-acids.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092981.Ratio-of-saturated-fatty-acids-to-total-fatty-acids --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092985.Total-cholesterol-levels.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092985.Total-cholesterol-levels --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90092987.Total-fatty-acid-levels.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90092987.Total-fatty-acid-levels --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90093002.Average-diameter-for-VLDL-particles.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90093002.Average-diameter-for-VLDL-particles --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90269502.LDL-cholesterol-levels-UKB-data-field-23405.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90269502.LDL-cholesterol-levels-UKB-data-field-23405 --a1-inc --chunksize 500000
python /workspace/rsrch1/ychen/bin/ldsc/munge_sumstats.py --sumstats /mnt/disk/LDSC/sumstats/Lipid_or_lipoprotein_measurement.GCST90269582.Cholesteryl-esters-in-chylomicrons-and-extremely-large-VLDL-UKB-data-field-23485.sumstats --merge-alleles /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/w_hm3.snplist --out /workspace/rsrch1/ychen/Projects/Project03_human_circadian/rQTL/cis_QTL/03_enrich_GWAS/LDSC/sumstats/GWAScata_sumstats/Lipid_or_lipoprotein_measurement.GCST90269582.Cholesteryl-esters-in-chylomicrons-and-extremely-large-VLDL-UKB-data-field-23485 --a1-inc --chunksize 500000
