sh 2_QTL_annotation_LDscore.sh Liver 1
sh 2_QTL_annotation_LDscore.sh Liver 2
sh 2_QTL_annotation_LDscore.sh Liver 3
sh 2_QTL_annotation_LDscore.sh Liver 4
sh 2_QTL_annotation_LDscore.sh Liver 5
sh 2_QTL_annotation_LDscore.sh Liver 6
sh 2_QTL_annotation_LDscore.sh Liver 7
sh 2_QTL_annotation_LDscore.sh Liver 8
sh 2_QTL_annotation_LDscore.sh Liver 9
sh 2_QTL_annotation_LDscore.sh Liver 10
sh 2_QTL_annotation_LDscore.sh Liver 11
sh 2_QTL_annotation_LDscore.sh Liver 12
sh 2_QTL_annotation_LDscore.sh Liver 13
sh 2_QTL_annotation_LDscore.sh Liver 14
sh 2_QTL_annotation_LDscore.sh Liver 15
sh 2_QTL_annotation_LDscore.sh Liver 16
sh 2_QTL_annotation_LDscore.sh Liver 17
sh 2_QTL_annotation_LDscore.sh Liver 18
sh 2_QTL_annotation_LDscore.sh Liver 19
sh 2_QTL_annotation_LDscore.sh Liver 20
sh 2_QTL_annotation_LDscore.sh Liver 21
sh 2_QTL_annotation_LDscore.sh Liver 22
