sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST000755.HDL-cholesterol
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST002216.Triglycerides
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092808.Apolipoprotein-A1-levels
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092809.Apolipoprotein-B-levels
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092875.Concentration-of-large-VLDL-particles
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092928.Monounsaturated-fatty-acid-levels
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092975.Concentration-of-small-VLDL-particles
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092980.Saturated-fatty-acid-levels
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092981.Ratio-of-saturated-fatty-acids-to-total-fatty-acids
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90092987.Total-fatty-acid-levels
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90093002.Average-diameter-for-VLDL-particles
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90269582.Cholesteryl-esters-in-chylomicrons-and-extremely-large-VLDL-UKB-data-field-23485
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90269553.Linoleic-acid-to-total-fatty-acids-percentage-UKB-data-field-23456
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST002221.Cholesterol-total
sh 3_Heritability.sh Liver Lipid_or_lipoprotein_measurement.GCST90267273.LDL-weighted-GWA
